### ISSUE TITLE
Is there a min. memory requirement?

### ISSUE THREAD

**Issue by Sechorda** [hadriansecurity/sanicdns#27]
I got this error trying this tool out on a crostini ChromeOS container with 3GB mem.

sechorda@penguin:~$ sudo sanicdns -i majestic_million.txt --resolvers 1.1.1.1,1.0.0.1 -o out.txt --no-huge
EAL: Detected CPU lcores: 2
EAL: Detected NUMA nodes: 1
EAL: Static memory layout is selected, amount of reserved memory can be adjusted with -m or --socket-mem
EAL: Detected static linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
TELEMETRY: No legacy callbacks, legacy socket not created

**Comment by Sechorda** [comment]
> Hey there! SanicDNS should be able to run well within the 1Gb limit. I've personally also had issues with using DPDK's option to not use hugepages, can you try without `--no-huge` with hugepages or does your ChromeOS container not support hugepages?

ChromeOS doesn't support huge pages, but I am interested in ripping out amass in my custom BB image and tool flow with sanic, as amass is my largest time-sink. this would patch a huge hole in my workflow and save me time in the long run. So I wanted to test the results on ChromeOS before modifying my OS build. No biggie though, I can boot the OS and test there...

**Comment by kalmjasper** [comment]
Also let us know if you experience any other issues / have other suggestions. Would love to hear it

**Comment by Sechorda** [comment]
> Also let us know if you experience any other issues / have other suggestions. Would love to hear it

Thanks for the chat. virt environment bottlenecks makes sense, and would not be ideal to focus on supporting. Cheers. let's close this.
